import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { load as loadYaml } from 'js-yaml';
import { getOriginUrl, parseGithubOwner } from './git-remote.js';

// CLAUDE.local.md is generated from a personal library of markdown fragments,
// each optionally scoped to a repo org and/or isolation mode via YAML
// frontmatter. See the design discussion this implements: matching is AND
// across frontmatter keys, OR within a key's list, a missing key is a
// wildcard for that dimension, and no frontmatter at all means "always
// included". Any malformed fragment aborts generation — this feature never
// silently degrades, matching the rest of this tool's settings handling.

export type Isolation = 'proxy' | 'sbx';

export interface Fragment {
  /** Absolute path to the fragment file. */
  path: string;
  org?: string[];
  isolation?: string[];
  body: string;
}

export interface MatchContext {
  /** Lowercased repo owner, or undefined when there's no org to match (e.g. no git remote). */
  org: string | undefined;
  isolation: Isolation;
}

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/;
const KNOWN_FRONTMATTER_KEYS = new Set(['org', 'isolation']);

function toStringList(value: unknown, key: string, path: string): string[] {
  if (typeof value === 'string') return [value];
  if (Array.isArray(value) && value.every(v => typeof v === 'string')) return value as string[];
  throw new Error(`${path}: "${key}" must be a string or an array of strings, got ${JSON.stringify(value)}`);
}

/** Parses a fragment's optional YAML frontmatter and body. Throws on any malformed frontmatter. */
export function parseFragment(content: string, path: string): Fragment {
  const match = content.match(FRONTMATTER_RE);
  if (!match) return { path, body: content };

  // Both groups are non-optional in FRONTMATTER_RE, so they're always present
  // when the overall match succeeds; `?? ''` only appeases noUncheckedIndexedAccess.
  const frontmatterYaml = match[1] ?? '';
  const body = match[2] ?? '';
  let raw: unknown;
  try {
    raw = loadYaml(frontmatterYaml);
  } catch (e) {
    throw new Error(`${path}: invalid frontmatter YAML: ${e instanceof Error ? e.message : String(e)}`);
  }
  if (raw === undefined || raw === null) return { path, body };
  if (typeof raw !== 'object' || Array.isArray(raw)) {
    throw new Error(`${path}: frontmatter must be a YAML mapping`);
  }

  const obj = raw as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    if (!KNOWN_FRONTMATTER_KEYS.has(key)) {
      throw new Error(`${path}: unrecognized frontmatter key "${key}" (known keys: org, isolation)`);
    }
  }

  // exactOptionalPropertyTypes forbids assigning `org: undefined` — spread in
  // the key only when the frontmatter actually set it.
  const org = 'org' in obj ? { org: toStringList(obj['org'], 'org', path) } : {};
  const isolation = 'isolation' in obj ? { isolation: toStringList(obj['isolation'], 'isolation', path) } : {};

  return { path, ...org, ...isolation, body };
}

function matchesList(list: string[] | undefined, value: string | undefined, caseInsensitive: boolean): boolean {
  if (!list) return true; // key absent -> wildcard for this dimension
  if (value === undefined) return false;
  const needle = caseInsensitive ? value.toLowerCase() : value;
  return list.some(v => (caseInsensitive ? v.toLowerCase() : v) === needle);
}

/** AND across frontmatter keys, OR within a key's list, missing key = wildcard. */
export function fragmentMatches(fragment: Fragment, context: MatchContext): boolean {
  return (
    matchesList(fragment.org, context.org, true) &&
    matchesList(fragment.isolation, context.isolation, false)
  );
}

export type RepoOwnerResult =
  | { kind: 'github'; owner: string }
  | { kind: 'no-remote' }
  | { kind: 'unsupported-remote'; url: string };

/** No remote at all is not an error — it just means no org-scoped fragment can match. A non-GitHub remote is. */
export function detectRepoOwner(): RepoOwnerResult {
  const url = getOriginUrl();
  if (!url) return { kind: 'no-remote' };
  const owner = parseGithubOwner(url);
  if (!owner) return { kind: 'unsupported-remote', url };
  return { kind: 'github', owner };
}

function renderHeader(fragmentsDir: string): string {
  return [
    '<!--',
    '  AUTO-GENERATED by safe-agent-cli. Do not edit this file directly — your',
    '  edits will be silently overwritten on the next launch.',
    '',
    `  Edit the source fragments instead, in: ${fragmentsDir}`,
    '-->',
    '',
  ].join('\n');
}

// The header already points at fragmentsDir's full path, so each fragment's
// provenance comment only needs its filename — repeating the full path per
// fragment would burn tokens on every launch for no added information.
function renderFragment(fragment: Fragment): string {
  return `<!-- fragment: ${basename(fragment.path)} -->\n${fragment.body.trim()}\n`;
}

/** Expands a leading `~` or `~/...` against `home`. Leaves other paths untouched. */
export function expandHome(path: string, home: string): string {
  if (path === '~') return home;
  if (path.startsWith('~/')) return join(home, path.slice(2));
  return path;
}

export interface GenerateResult {
  outputPath: string;
  matchedCount: number;
  totalCount: number;
  rtkAppended: boolean;
}

/**
 * Reads every `*.md` fragment in `fragmentsDir`, keeps the ones whose
 * frontmatter matches the current repo/isolation context, and writes the
 * concatenated result to `CLAUDE.local.md` in `repoRoot`. Fragments are
 * ordered alphabetically by filename. When `rtkMdPath` is given, its content
 * is read and appended last, unconditionally, exactly like a fragment with no
 * frontmatter — this is how `checkRtk` users get RTK.md into context now,
 * instead of a hand-maintained `@RTK.md` import in CLAUDE.md. Throws on any
 * failure (missing fragments directory, malformed fragment, unsupported git
 * remote, missing rtkMdPath) — the caller is expected to treat that as fatal.
 */
export function generateClaudeLocalMd(
  fragmentsDir: string,
  repoRoot: string,
  isolation: Isolation = 'proxy',
  rtkMdPath?: string,
): GenerateResult {
  if (!existsSync(fragmentsDir)) {
    throw new Error(`claudeFragmentsDir does not exist: ${fragmentsDir}`);
  }

  const ownerResult = detectRepoOwner();
  if (ownerResult.kind === 'unsupported-remote') {
    throw new Error(
      `origin remote is not a GitHub remote (${ownerResult.url}) — cannot evaluate org-scoped fragments`,
    );
  }
  const org = ownerResult.kind === 'github' ? ownerResult.owner : undefined;

  const filenames = readdirSync(fragmentsDir).filter(f => f.endsWith('.md')).sort();
  const fragments = filenames.map(f => {
    const path = join(fragmentsDir, f);
    return parseFragment(readFileSync(path, 'utf8'), path);
  });

  const matched = fragments.filter(f => fragmentMatches(f, { org, isolation }));
  const sections = matched.map(renderFragment);

  const rtkAppended = rtkMdPath !== undefined;
  if (rtkMdPath !== undefined) {
    if (!existsSync(rtkMdPath)) {
      throw new Error(`checkRtk is enabled but ${rtkMdPath} does not exist — run: rtk init -g`);
    }
    sections.push(renderFragment({ path: rtkMdPath, body: readFileSync(rtkMdPath, 'utf8') }));
  }

  const content = [renderHeader(fragmentsDir), ...sections].join('\n');
  const outputPath = join(repoRoot, 'CLAUDE.local.md');
  writeFileSync(outputPath, content, 'utf8');

  return { outputPath, matchedCount: matched.length, totalCount: fragments.length, rtkAppended };
}
